# ============================================================
# UYIR — Threshold Analyzer
# Manikandan — Task M4
#
# Load the CSV generated by data_logger.py.
# Plots accident vs normal distribution for each factor.
# Finds the threshold value that separates them best.
# Update config.py with the suggested values.
#
# Usage:
#   python threshold_analyzer.py --csv uyir_data_log.csv
# ============================================================

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import numpy as np
import argparse
import os
import config


def analyze(csv_path: str):
    print(f"\n[Analyzer] Loading: {csv_path}")
    df = pd.read_csv(csv_path)

    acc = df[df["label"] == "accident"]
    nor = df[df["label"] == "normal"]

    print(f"[Analyzer] Total rows      : {len(df)}")
    print(f"[Analyzer] Accident rows   : {len(acc)}")
    print(f"[Analyzer] Normal rows     : {len(nor)}")
    print(f"[Analyzer] Unique videos   : {df['video_file'].nunique()}")

    factors = [
        {
            "col"       : "nearest_euclidean_dist",
            "name"      : "Phase A — Nearest Euclidean Distance (px)",
            "threshold" : config.PROXIMITY_THRESHOLD,
            "direction" : "below",   # trigger when BELOW threshold
        },
        {
            "col"       : "speed_drop_percent",
            "name"      : "Phase B — Speed Drop %",
            "threshold" : config.SPEED_DROP_PERCENT,
            "direction" : "above",
        },
        {
            "col"       : "trajectory_deviation_px",
            "name"      : "Phase B — Trajectory Deviation (px)",
            "threshold" : 40.0,
            "direction" : "above",
        },
        {
            "col"       : "optical_flow_ratio",
            "name"      : "Phase C — Optical Flow Ratio",
            "threshold" : config.OPTICAL_FLOW_SPIKE,
            "direction" : "above",
        },
        {
            "col"       : "bbox_area_change_ratio",
            "name"      : "Phase C — BBox Area Change Ratio",
            "threshold" : config.BBOX_DEFORM_RATIO,
            "direction" : "above",
        },
        {
            "col"       : "accident_model_confidence",
            "name"      : "Stage 1 — Accident Model Confidence",
            "threshold" : config.STAGE1_GATE_CONFIDENCE,
            "direction" : "above",
        },
    ]

    fig = plt.figure(figsize=(20, 16))
    fig.suptitle(
        "UYIR — Threshold Analysis\n"
        "Accident vs Normal Traffic Factor Distributions",
        fontsize=14, fontweight="bold", y=0.99
    )
    gs  = gridspec.GridSpec(3, 2, figure=fig, hspace=0.50, wspace=0.30)
    axes = [fig.add_subplot(gs[i//2, i%2]) for i in range(len(factors))]

    print("\n" + "="*65)
    print("  FACTOR STATISTICS")
    print("="*65)

    suggestions = {}

    for ax, f in zip(axes, factors):
        col = f["col"]
        if col not in df.columns:
            ax.set_title(f["name"] + " (no data)")
            continue

        p99_a = np.percentile(acc[col].dropna(), 99) if len(acc) else 1
        p99_n = np.percentile(nor[col].dropna(), 99) if len(nor) else 1
        clip_val = max(p99_a, p99_n)

        acc_col = acc[col].dropna().clip(upper=clip_val)
        nor_col = nor[col].dropna().clip(upper=clip_val)

        ax.hist(nor_col, bins=50, alpha=0.6, color="#2196F3",
                label=f"Normal (n={len(nor_col)})", density=True)
        ax.hist(acc_col, bins=50, alpha=0.6, color="#F44336",
                label=f"Accident (n={len(acc_col)})", density=True)

        if f["threshold"] is not None:
            ax.axvline(f["threshold"], color="orange", linewidth=2,
                       linestyle="--",
                       label=f"Current = {f['threshold']}")

        # Find best threshold using F1
        best_t, best_f1 = _find_best_threshold(
            acc_col, nor_col, f["direction"]
        )
        ax.axvline(best_t, color="green", linewidth=1.5,
                   linestyle=":", label=f"Suggested = {best_t:.3f}")
        suggestions[col] = best_t

        ax.set_title(f["name"], fontweight="bold", fontsize=10)
        ax.set_xlabel("Value")
        ax.set_ylabel("Density")
        ax.legend(fontsize=8)
        ax.grid(alpha=0.3)

        # Print stats
        print(f"\n  {f['name']}")
        if len(nor_col):
            print(f"    Normal   mean={nor_col.mean():.3f} "
                  f"median={nor_col.median():.3f} "
                  f"p90={np.percentile(nor_col,90):.3f}")
        if len(acc_col):
            print(f"    Accident mean={acc_col.mean():.3f} "
                  f"median={acc_col.median():.3f} "
                  f"p90={np.percentile(acc_col,90):.3f}")
        print(f"    Current threshold : {f['threshold']}")
        print(f"    Suggested (F1)    : {best_t:.3f}  (F1={best_f1:.3f})")

    plt.tight_layout()
    out_plot = csv_path.replace(".csv", "_distributions.png")
    plt.savefig(out_plot, dpi=150, bbox_inches="tight")
    print(f"\n[Analyzer] Saved: {out_plot}")

    # ── Score distribution ────────────────────────────────────
    _plot_scores(df, acc, nor, csv_path)

    # ── Recommendation summary ────────────────────────────────
    print("\n" + "="*65)
    print("  SUGGESTED config.py UPDATES")
    print("="*65)
    mapping = {
        "nearest_euclidean_dist"   : "PROXIMITY_THRESHOLD",
        "speed_drop_percent"       : "SPEED_DROP_PERCENT",
        "optical_flow_ratio"       : "OPTICAL_FLOW_SPIKE",
        "bbox_area_change_ratio"   : "BBOX_DEFORM_RATIO",
        "accident_model_confidence": "STAGE1_GATE_CONFIDENCE",
    }
    for col, cfg_key in mapping.items():
        if col in suggestions:
            print(f"  {cfg_key:35s} = {suggestions[col]:.3f}")
    print("="*65)
    print("\nUpdate config.py with the suggested values above.")
    print("Run again on new test clips to verify the new thresholds.\n")

    plt.show()


def _plot_scores(df, acc, nor, csv_path):
    """Plot distribution of total factor scores for accident vs normal."""
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))
    fig.suptitle("UYIR — Total Score Distribution",
                 fontsize=12, fontweight="bold")

    for ax, data, title, color in [
        (ax1, nor, "Normal Traffic", "#2196F3"),
        (ax2, acc, "Accident Clips", "#F44336"),
    ]:
        scores = _compute_simple_scores(data)
        ax.hist(scores, bins=range(0, 9), color=color,
                alpha=0.8, edgecolor="white")
        ax.axvline(config.MIN_SCORE_TO_PASS, color="orange",
                   linewidth=2, linestyle="--",
                   label=f"Gate = {config.MIN_SCORE_TO_PASS}")
        ax.set_title(title, fontweight="bold")
        ax.set_xlabel("Score (0-7)")
        ax.set_ylabel("Frame Count")
        ax.legend()
        ax.grid(alpha=0.3)

    plt.tight_layout()
    out = csv_path.replace(".csv", "_scores.png")
    plt.savefig(out, dpi=150, bbox_inches="tight")
    print(f"[Analyzer] Saved: {out}")


def _compute_simple_scores(df_subset) -> list:
    scores = []
    for _, row in df_subset.iterrows():
        s = 0
        try:
            if float(row["nearest_euclidean_dist"]) < config.PROXIMITY_THRESHOLD:
                s += config.SCORE_PHASE_A
            if float(row["speed_drop_percent"]) > config.SPEED_DROP_PERCENT:
                s += config.SCORE_PHASE_B
            if float(row["optical_flow_ratio"]) > config.OPTICAL_FLOW_SPIKE:
                s += config.SCORE_PHASE_C
        except Exception:
            pass
        scores.append(s)
    return scores


def _find_best_threshold(pos_vals, neg_vals, direction: str) -> tuple:
    """Find threshold maximising F1 score."""
    all_vals = pd.concat([pos_vals, neg_vals]).dropna().sort_values()
    if len(all_vals) == 0:
        return 0.5, 0.0

    best_t  = float(all_vals.median())
    best_f1 = 0.0

    lo = float(all_vals.quantile(0.05))
    hi = float(all_vals.quantile(0.95))

    for t in np.linspace(lo, hi, 60):
        if direction == "above":
            tp = (pos_vals > t).sum()
            fp = (neg_vals > t).sum()
            fn = (pos_vals <= t).sum()
        else:  # below
            tp = (pos_vals < t).sum()
            fp = (neg_vals < t).sum()
            fn = (pos_vals >= t).sum()

        p  = tp / (tp + fp) if (tp + fp) > 0 else 0
        r  = tp / (tp + fn) if (tp + fn) > 0 else 0
        f1 = 2*p*r/(p+r) if (p+r) > 0 else 0

        if f1 > best_f1:
            best_f1 = f1
            best_t  = t

    return best_t, best_f1


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="UYIR Threshold Analyzer")
    parser.add_argument("--csv", required=True,
                        help="CSV file from data_logger.py")
    args = parser.parse_args()

    if not os.path.exists(args.csv):
        print(f"[Analyzer] File not found: {args.csv}")
    else:
        analyze(args.csv)
